### ISSUE TITLE
Blank white screen in First run

### ISSUE THREAD

**Issue by rikkinovar** [OsmiCSX/osmi#7]
blank white screen in first run
![image](https://user-images.githubusercontent.com/3031154/120157880-aef40580-c21d-11eb-878d-0b939e63f642.png)

**Comment by DeVoresyah** [comment]
> blank white screen in first run
> ![image](https://user-images.githubusercontent.com/3031154/120157880-aef40580-c21d-11eb-878d-0b939e63f642.png)

can you tell me more details about this?

**Comment by DeVoresyah** [comment]
We already fix this issue, I think this is because of the `SafeAreaView` in the `RootContainer.js` doesn't have flex style
